swagger: "2.0"
info:
  description: "This is a sample of a creating a board"
  version: "1.0.0-beta"
  title: "Swagger Todo BoardController"
  license:
    name: "Apache 2.0"
    url: "http://localhost:8080"
host: "localhost"
tags:
- name: "todo-board"
  description: "Everything about your card on the board"
- name: "users"
  description: "Operations about user"
schemes:
- "https"
paths:
  /boards:
    post:
      tags:
      - "todo-board"
      summary: "Add a new board"
      description: "Create new todo cards"
      operationId: "store"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Card object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/BoardController"
      responses:
        201:
         description: "Operation created successfully"
         schema:
           $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
    get:
      tags:
      - "todo-board"
      summary: "This show all the cards"
      description: ""
      operationId: "index"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "body"
        required: true
        schema:
         $ref: "#/definitions/BoardController"
      responses:
        200:
         description: "Operation was successfully"
         schema:
           $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
  /boards/{id}:
     post:
      tags:
      - "todo-board"
      summary: "Update an existing card"
      description: "Card object that needs to be updated to the store"
      operationId: "update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        description: "Card id to update"
        required: true
        type: "string"
      responses:
        200:
         description: "Operation was successfully"
         schema:
           $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
     delete:
      tags:
      - "todo-board"
      summary: "Delete a card"
      description: ""
      operationId: "delete"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        type: "integer"
        description: "Card id to delete"
        required: true
      responses:
        200:
         description: "Operation was successfully"
         schema:
           $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
  /users:
    post:
      tags:
      - "users"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "registerUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/User"
      responses:
        201:
          schema:
            $ref: "#/definitions/ApiResponse"
          description: "successful operation"
  /user/login:
    get:
      tags:
      - "users"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "users"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_token:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      created_at:
        type: "string"
      updated_at:
        type: "string"
      deleted_at:
        type: "string"
  TodoBoard:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_id:
        type: "string"
      name:
        type: "string"
      created_at:
        type: "string"
      updated_at:
        type: "string"
      deleted_at:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      data:
        type: "object"
      status:
        type: "string"
